#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, you can try the following workarounds:
#       - use `bash`
#       - use `sh` from ksh
#       - install ksh
#       - install bash
#
#   (2) The slashes in the paths are important on Windows (for PathConvert).
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -L "$app_path" ]
do
    app_path=$(readlink "$app_path") || exit
    APP_HOME=${app_path%"${app_path##*/}"}
done

# This is normally unused
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME:-.}" && pwd -P) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    echo "$*" >&2
}

die() {
    echo "$*" >&2
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
CYGWIN*) cygwin=true ;;
Darwin*) darwin=true ;;
MSYS* | MINGW*) msys=true ;;
NONSTOP*) nonstop=true ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" "$LINENO"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
    case $MAX_FD in
    /*)
        MAX_FD=$(stat -f%z "$MAX_FD")
        ;;
    *)
        MAX_FD=$(ulimit -n)
        ;;
    esac
fi

# Escape application home to make it safe to pass to log4j
APP_HOME_STR=$(echo "$APP_HOME" | sed 's/[[:space:]]/\\ /g')

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    echo "$*" >&2
}

die() {
    echo "$*" >&2
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
CYGWIN*) cygwin=true ;;
Darwin*) darwin=true ;;
MSYS* | MINGW*) msys=true ;;
NONSTOP*) nonstop=true ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" "$LINENO"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
    case $MAX_FD in
    /*)
        MAX_FD=$(stat -f%z "$MAX_FD")
        ;;
    *)
        MAX_FD=$(ulimit -n)
        ;;
    esac
fi

# Escape application home to make it safe to pass to log4j
APP_HOME_STR=$(echo "$APP_HOME" | sed 's/[[:space:]]/\\ /g')

eval "set -- $(getopt -o '' -l classpath:,coverageDir:,coverageInstrumentationIncludes:,distributedTest,failFast,fs:,gradle -l gradle,gradleUserHomeDir:,hostTempDir:,importTest,jacocoAgent,jacocoDir:,javaAgent:,jacocoReport,jacocoReportFile:,libDir:,listTests,maxWorkers:,myPathSeparator:,myRepositoryUrl:,name:,parallel,postBuild,profile,sharedBuildCache,sharedMemoryDirectory:,testCoverageClasspath:,testCoverageRootDir:,testCoverageSourceDir:,testCoordinates:,testDependencies:,testIntegration,testSystemProperties:,underTest,updateAllDeps,versionFile:,versionLatest,versionOlder -n "$0" -- "$@")"

# Escape application home to make it safe to pass to log4j
APP_HOME_STR=$(echo "$APP_HOME" | sed 's/[[:space:]]/\\ /g')

# Check for cygwin and convert paths.
if $cygwin; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    APP_HOME=$(cygpath --path --mixed "$JAVA_HOME")
    [ -n "$CP" ] && CP=$(cygpath --path --mixed "$CP")
fi

# Expand the number of file descriptors on Mac OS X and Linux.
if ! "$cygwin" && ! "$msys"; then
    eval "ulimit -n 16384"
fi

exec "$JAVACMD" $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain "$@"
